Add fix suffix by mimetype to file processing
IndicoDataSolutions/Indico-Solutions-Toolkit pull request #71
Opened 2021-07-21 20:54 UTC by jonaskaz

- adds python-magic dependency, the python module mimetype only includes a method that guesses mimetype by file suffix which would not work for this application

2021-07-21 21:57 UTC, Scott771 commented
https://github.com/ahupp/python-magic

Doesn't this require OS specific installations?

2021-07-21 21:57 UTC, Scott771 commented
if those dependencies aren't installed, how is the error handling?

2021-07-21 21:59 UTC, Scott771 commented on indico_toolkit/pipelines/file_processing.py
> +    def fix_file_suffixes(
is this renaming the files in place on the system??

2021-07-21 22:00 UTC, Scott771 commented on indico_toolkit/pipelines/file_processing.py
> +    def fix_file_suffixes(
think that should be clearer or optional

2021-07-21 22:31 UTC, Scott771 commented on indico_toolkit/pipelines/file_processing.py
> +    def fix_file_suffixes(
I would also probably be more opinionated with how the function works, i.e. I don' think we need to give the option to pass a mime_suffix_mapping (I would have no idea what to do with this)

2021-07-21 22:33 UTC, Scott771 commented on setup.py
> +        "python-magic>=0.4.24"
If you are using new pip installed libraries, make sure they are added to the setup.py and pyproject.toml (only pyproject.toml actually determines what gets installed as dependencies via pip)

2021-07-21 22:34 UTC, Scott771 requested changes
check python-magic requirements for different OS, if OK to use, then also add to .toml

2021-07-22 13:34 UTC, jonaskaz commented
python-magic has os specific installation, will leave this feature as a standalone script

2021-07-22 13:34 UTC, closed without merging